services:
  database:
    image: postgres:16.4
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"
    volumes:
      - ./cache/postgres/data:/var/lib/postgresql/data
    user: "${UID}:${GID}"

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "6969:8080"
    command:
      - start-dev
    volumes:
      - ./cache/keycloak/data:/opt/keycloak/data
    user: "${UID}:${GID}"

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./cache/minio/data:/data
    user: "${UID}:${GID}"
    command: server /data --console-address ":9001"

  qdrant:
    image: qdrant/qdrant:v1.14.1
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./cache/qdrant:/qdrant/storage:z

  nats:
    image: nats:2.11.4-linux
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command:
      - -js
      - -sd
      - /data
    volumes:
      - ./cache/nats:/data
    user: "${UID}:${GID}"